version: 2.1

orbs:
  node: circleci/node@4.7.0  

# default pipeline parameters, which will be updated according to
# the results of the path-filtering orb
parameters:
  build-app-job:
    type: boolean
    default: false
  build-shared-job:
    type: boolean
    default: false
  build-all-job:
    type: boolean
    default: false  
  build-contentfully-job:
    type: boolean
    default: false  

# conditional workflows
# executed based upon pipeline parameter values. Each workflow calls a
# specific job defined below

jobs:
  build-app:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn      
      - run:
          command: |
            yarn workspace app build
            ls
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  
  build-shared:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn      
      - run:
          command: |
            yarn workspace shared build
            ls
          name: Build shared
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  build-contentfully:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn      
      - run:
          command: |
            yarn workspace contentfully build
            ls
          name: Build contentfully
      - persist_to_workspace:
          root: ~/project
          paths:
            - .          
            
  deploy-app:
    working_directory: ~/project
    docker:
      - image: innovatorjapan/awscli:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: |
            echo "Going to deploy app"
            ls
            if [ $CIRCLE_BRANCH = 'main' ]; then
              aws s3 sync packages/app/dist s3://federated-module-host-app --delete --exact-timestamps;
            fi

  deploy-shared:
    working_directory: ~/project
    docker:
      - image: innovatorjapan/awscli:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: |
            echo "Going to deploy shared"
            ls
            if [ $CIRCLE_BRANCH = 'main' ]; then
              aws s3 sync packages/shared/dist s3://federated-module-shared --delete --exact-timestamps;
            fi
  
  deploy-contentfully:
    working_directory: ~/project
    docker:
      - image: innovatorjapan/awscli:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: |
            echo "Going to deploy Contentfully"
            ls
            if [ $CIRCLE_BRANCH = 'main' ]; then
              aws s3 sync packages/contentfully/dist s3://federated-module-contenfully --delete --exact-timestamps;
            fi
  
workflows:
  build-app-job:
    when: << pipeline.parameters.build-app-job >>
    jobs:
      - build-app
      - deploy-app:
          filters:
            branches:
              only:
                - main
          requires:
              - build-app          

  build-shared-job:
    when: << pipeline.parameters.build-shared-job >>
    jobs:
      - build-shared
      - deploy-shared:
          filters:
            branches:
              only:
                - main
          requires:
              - build-shared

  build-contentfully-job:
    when: << pipeline.parameters.build-shared-job >>
    jobs:
      - build-contentfully
      - deploy-contentfully:
          filters:
            branches:
              only:
                - main
          requires:
              - build-contentfully                        
  
  build-all-job:
    when: << pipeline.parameters.build-all-job >>
    jobs:
      - build-shared
      - deploy-shared:
          filters:
            branches:
              only:
                - main
          requires:
              - build-shared
      - build-contentfully
      - deploy-contentfully:
          filters:
            branches:
              only:
                - main
          requires:
              - build-contentfully
      - build-app
      - deploy-app:
          filters:
            branches:
              only:
                - main
          requires:
              - build-app  