version: 2.1

orbs:
  node: circleci/node@4.7.0  

# default pipeline parameters, which will be updated according to
# the results of the path-filtering orb
parameters:
  build-app-job:
    type: boolean
    default: false
  build-shared-job:
    type: boolean
    default: false

# conditional workflows
# executed based upon pipeline parameter values. Each workflow calls a
# specific job defined below

jobs:
  build-app:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn      
      - run:
          command: yarn workspace app build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  
  build-shared:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn      
      - run:
          command: yarn workspace shared build
          name: Build shared
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  
workflows:
  # triggers when pipeline parameter build-app-job is true
  build-app-job:
    when: << pipeline.parameters.build-app-job >>
    jobs:
      - build-app

  build-shared-job:
    when: << pipeline.parameters.build-shared-job >>
    jobs:
      - build-shared